all:
  children:
    osds:
      hosts:
        192.168.140.252:
          ansible_user: ljishen
          data_disks:
            - /dev/sda1
            - /dev/sda2

    mons:
      hosts:
        192.168.140.138:
          ansible_user: ljishen

    mgrs:
      hosts:
        192.168.140.138:
          ansible_user: ljishen

    admins:
      hosts:
        localhost:
          ansible_user: ljishen
          ansible_connection: local
          ansible_python_interpreter: '{{ ansible_playbook_python }}'
