---
- name: install logical volume management tools
  become: yes
  apt:
    cache_valid_time: '{{ 60 * 60 * 24 }}' # cache is valid in a day
    install_recommends: no
    name:
      - lvm2=2.02*
      - dmsetup=2:1.*
    state: present
    update_cache: yes

- include_tasks: rm.yml
  loop: '{{ data_disks }}'
  loop_control:
    loop_var: disk
