---
- name: install logical volume management tools
  become: yes
  apt:
    install_recommends: no
    name:
      - lvm2=2.02*
      - dmsetup=2:1.*
    state: present
    update_cache: yes

- include_tasks: rm.yml
  loop: '{{ data_disks }}'
  loop_control:
    loop_var: disk
